# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('customer', models.PositiveSmallIntegerField(blank=True, choices=[(0, b'All'), (1, b'male'), (2, b'female')], null=True)),
                ('price', models.FloatField()),
                ('area', models.FloatField()),
                ('province', models.CharField(max_length=140)),
                ('district', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=b'image')),
                ('video', models.FileField(upload_to=b'video')),
                ('decription', models.TextField()),
                ('like_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('facebook', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserHasPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoAnApi.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoAnApi.User')),
            ],
        ),
    ]
