# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoAnApi', '0002_userlikepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoAnApi.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoAnApi.User')),
            ],
        ),
    ]
