# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoAnApi', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhaspost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userhaspost',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DoAnApi.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserHasPost',
        ),
    ]
