# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoAnApi', '0008_auto_20171123_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Admin'), (2, b'User')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Inactive'), (1, b'Active')], default=0),
        ),
    ]
